select * from EMPLOYEES;

select FIRST_NAME, SALARY FROM EMPLOYEES
WHERE SALARY > 7000 AND DEPARTMENT_ID = 80;


SELECT FIRST_NAME, LAST_NAME, SALARY
 FROM EMPLOYEES WHERE SALARY> 3000 AND SALARY < 6000;

--Write the same clause with the word between.

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM EMPLOYEES WHERE SALARY BETWEEN 3000 AND 6000;---BETWEEN will include the range as well.

--fROM EMPLOYEES WHERE JOB IT-PROG OR JOB ID SA-REP.
select * FROM EMPLOYEES WHERE JOB_ID = 'IT_PROG' OR JOB_ID ='SA_REP';










