
SELECT * FROM EMPLOYEES;

SELECT FIRST_NAME FROM EMPLOYEES;---THIS WILL SHOW ALL THE NAMES IN THE TABLE

SELECT DISTINCT FIRST_NAME FROM EMPLOYEES;----THIS WILL REMOVE ALL DUPLICATES IN THE TABLE


--GET ME UNIQUE COUNTRY IDS FROM LOCATIONS
SELECT DISTINCT COUNTRY_ID FROM LOCATIONS;
SELECT COUNTRY_ID FROM LOCATIONS;

---GET ME A UNIQUE JOB IDS FROM JOBS
select distinct JOB_ID FROM JOBS;
select JOB_ID from JOBS;



